---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-root-ca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: root-ca
    spec:
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc
      containers:
      - name: root-ca
        image: hyperledger/fabric-ca:1.4
        # TODO remove sleep 
        command: ["bash", "-c", "chmod +x ./shared/artifacts/root-ca-startup.sh; ./shared/artifacts/root-ca-startup.sh; sleep 30"]
        env:
        - name: FABRIC_CA_SERVER_CA_NAME
          value: "root-ca"
        - name: FABRIC_CA_SERVER_DEBUG
          value: "true"
        - name: FABRIC_CA_SERVER_HOME
          value: /etc/hyperledger/fabric-ca
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "false"
        - name: BOOTSTRAP_USER_PASS
          value: root-ca-testorg-admin:admin
        - name: TARGET_CERTFILE
          value: /shared/testorg-ca-cert.pem
        - name: FABRIC_ORGS
          value: testorg
        - name: GODEBUG
          value: "netdns=go"
        - name: FABRIC_CA_SERVER_CSR_CN
          value: "root-ca-testorg"
        - name: FABRIC_CA_SERVER_CSR_HOSTS
          value: "root-ca-testorg"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-intermediate-ca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: intermediate-ca
    spec:
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc
      containers:
      - name: intermediate-ca
        image: hyperledger/fabric-ca:1.4
        # TODO remove sleep
        command: ["bash", "-c", "sleep 10; chmod +x ./shared/artifacts/intermediate-ca-startup.sh; ./shared/artifacts/intermediate-ca-startup.sh; rm /shared/root-started;  sleep 20;"]
        env:
        - name: FABRIC_CA_SERVER_CA_NAME
          value: "intermediate-ca-testorg"
        - name: FABRIC_CA_SERVER_DEBUG
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "false"
        - name: FABRIC_CA_SERVER_HOME
          value: /etc/hyperledger/fabric-ca
        - name: BOOTSTRAP_USER_PASS
          value: intermediate-ca-testorg-admin:intermediate
        - name: TARGET_CERTFILE
          value: /shared/testorg-ca-cert.pem
        - name: TARGET_CHAINFILE
          value: /shared/testorg-ca-chain.pem
        - name: FABRIC_ORGS
          value: testorg
        - name: PARENT_URL
          value: http://root-ca-testorg-admin:admin@blockchain-root-ca:30056
        - name: GODEBUG
          value: "netdns=go"
        - name: FABRIC_CA_SERVER_CSR_HOSTS
          value: "intermediate-ca-testorg"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-root-ca
  labels:
    run: blockchain-root-ca
spec:
  type: ClusterIP
  selector:
    name: root-ca
  ports:
  - protocol: TCP
    targetPort: 7054
    port: 30056
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-intermediate-ca
  labels:
    run: blockchain-intermediate-ca
spec:
  type: ClusterIP
  selector:
    name: intermediate-ca
  ports:
  - protocol: TCP
    targetPort: 7054
    port: 30055
    name: grpc