apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka0
  name: kafka0
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka0
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka0"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_RETENTION_MS
          value: "-1"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "1000012 B"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "1048576 B"
        - name: KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES
          value: "10485760 B"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zk-0.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181,zk-1.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181,zk-2.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181"
        image: hyperledger/fabric-kafka:0.4.14
        name: kafka0
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka1
  name: kafka1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka1
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka1"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_RETENTION_MS
          value: "-1"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "1000012 B"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "1048576 B"
        - name: KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES
          value: "10485760 B"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zk-0.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181,zk-1.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181,zk-2.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181"
        image: hyperledger/fabric-kafka:0.4.14
        name: kafka1
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka2
  name: kafka2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka2
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka2"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_RETENTION_MS
          value: "-1"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "1000012 B"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "1048576 B"
        - name: KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES
          value: "10485760 B"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zk-0.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181,zk-1.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181,zk-2.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181"
        image: hyperledger/fabric-kafka:0.4.14
        name: kafka2
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka3
  name: kafka3
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka3
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka3"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_RETENTION_MS
          value: "-1"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "1000012 B"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "1048576 B"
        - name: KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES
          value: "10485760 B"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zk-0.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181,zk-1.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181,zk-2.zk-hs.{{NAMESPACE}}.svc.cluster.local:2181"
        image: hyperledger/fabric-kafka:0.4.14
        name: kafka3
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka0
  name: kafka0
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: kafka0
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka1
  name: kafka1
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: kafka1
status:
  loadBalancer: {}

--- 

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka2
  name: kafka2
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: kafka2
status:
  loadBalancer: {}

--- 

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka3
  name: kafka3
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: kafka3
status:
  loadBalancer: {}

