---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-orderer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: orderer
    spec:
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc
      containers:
      - name: orderer
        image: hyperledger/fabric-ca-orderer:1.2.1
        command: ["bash", "-c", "cd /opt/gopath/src/github.com/hyperledger/fabric/orderer; chmod +x /shared/artifacts/start-orderer.sh; ./shared/artifacts/start-orderer.sh"]
        # command: ["bash", "-c", "sleep 100000000000;"]
        env:
        - name: FABRIC_CA_CLIENT_HOME
          value: /etc/hyperledger/orderer
        - name: ENROLLMENT_URL
          value: http://orderer1:orderer1@blockchain-intermediate-ca:30055
        - name: ORDERER_GENERAL_ORDERERTYPE
          value: kafka
        - name: ORDERER_GENERAL_LEDGERTYPE
          value: ram
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LISTENPORT
          value: "31010"
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /etc/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: orbixorgMSP
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /shared/artifacts/genesis.block
        - name: ORDERER_GENERAL_GENESISPROFILE
          value: OrgOrdererGenesis
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "false"
        - name: GODEBUG
          value: "netdns=go"
        - name: CONFIGTX_ORDERER_KAFKA_BROKERS
          value: "[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]"
        - name: ORDERER_KAFKA_RETRY_SHORTTOTAL
          value: "30s"
        - name: ORDERER_KAFKA_VERBOSE
          value: "true"
        - name: CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT
          value: "10"
        - name: CONFIGTX_ORDERER_BATCHTIMEOUT
          value: "2s"
        - name: ORG_ADMIN_CERT
          value: /shared/orbixorg/msp/admincerts/cert.pem
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-org1peer1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: org1peer1
    spec:
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock

      containers:
      - name: org1peer1
        image: hyperledger/fabric-ca-peer:1.2.1
        command: ["bash", "-c", "chmod +x /shared/artifacts/start-peer.sh; ./shared/artifacts/start-peer.sh"]
        env:
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: CORE_PEER_ID
          value: org1peer1
        - name: CORE_PEER_ADDRESS
          value: blockchain-org1peer1:30110
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:30110
        - name: CORE_PEER_EVENTS_ADDRESS
          value: 0.0.0.0:30111
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: blockchain-org1peer1:30110
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
          value: "true"
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: blockchain-org1peer1:30110
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_LOCALMSPID
          value: orbixorgMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/orbixorg/peers/blockchain-org1peer1/msp/
        - name: CORE_LOGGING_LEVEL
          value: debug
        - name: CORE_LOGGING_PEER
          value: debug
        - name: CORE_LOGGING_CAUTHDSL
          value: debug
        - name: CORE_LOGGING_GOSSIP
          value: debug
        - name: CORE_LOGGING_LEDGER
          value: debug
        - name: CORE_LOGGING_MSP
          value: info
        - name: CORE_LOGGING_POLICIES
          value: debug
        - name: CORE_LOGGING_GRPC
          value: debug
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: goleveldb
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: blockchain-orderer:31010
        - name: GODEBUG
          value: "netdns=go"
        - name: CORE_VM_DOCKER_ATTACHSTDOUT
          value: "true"
        - name: ENROLLMENT_URL
          value: http://org1peer1:org1peer1@blockchain-intermediate-ca:30055
        - name: ORG_ADMIN_CERT
          value: /shared/orbixorg/msp/admincerts/cert.pem
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
